# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(817, 641)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tileset_grb = QtWidgets.QGroupBox(self.centralwidget)
        self.tileset_grb.setEnabled(True)
        self.tileset_grb.setObjectName("tileset_grb")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tileset_grb)
        self.gridLayout_2.setContentsMargins(-1, -1, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tileset_view = QtWidgets.QGraphicsView(self.tileset_grb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tileset_view.sizePolicy().hasHeightForWidth())
        self.tileset_view.setSizePolicy(sizePolicy)
        self.tileset_view.setMinimumSize(QtCore.QSize(280, 0))
        self.tileset_view.setMaximumSize(QtCore.QSize(320, 16777215))
        self.tileset_view.setObjectName("tileset_view")
        self.gridLayout_2.addWidget(self.tileset_view, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.tileset_grb)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.header_offset_txt = QtWidgets.QLineEdit(self.tileset_grb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_offset_txt.sizePolicy().hasHeightForWidth())
        self.header_offset_txt.setSizePolicy(sizePolicy)
        self.header_offset_txt.setMaximumSize(QtCore.QSize(100, 16777215))
        self.header_offset_txt.setReadOnly(True)
        self.header_offset_txt.setObjectName("header_offset_txt")
        self.gridLayout_2.addWidget(self.header_offset_txt, 0, 1, 1, 1)
        self.add_animation_btn = QtWidgets.QPushButton(self.tileset_grb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_animation_btn.sizePolicy().hasHeightForWidth())
        self.add_animation_btn.setSizePolicy(sizePolicy)
        self.add_animation_btn.setObjectName("add_animation_btn")
        self.gridLayout_2.addWidget(self.add_animation_btn, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tileset_grb)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.palette_cmb = QtWidgets.QComboBox(self.tileset_grb)
        self.palette_cmb.setMaximumSize(QtCore.QSize(60, 16777215))
        self.palette_cmb.setObjectName("palette_cmb")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.palette_cmb.addItem("")
        self.gridLayout_2.addWidget(self.palette_cmb, 1, 1, 1, 1)
        self.animations_grb = QtWidgets.QGroupBox(self.tileset_grb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animations_grb.sizePolicy().hasHeightForWidth())
        self.animations_grb.setSizePolicy(sizePolicy)
        self.animations_grb.setObjectName("animations_grb")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.animations_grb)
        self.gridLayout_3.setContentsMargins(-1, -1, 2, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frames_grb = QtWidgets.QGroupBox(self.animations_grb)
        self.frames_grb.setObjectName("frames_grb")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frames_grb)
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frames_grb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setContentsMargins(-1, -1, -1, 2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_lst = QtWidgets.QListWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_lst.sizePolicy().hasHeightForWidth())
        self.frame_lst.setSizePolicy(sizePolicy)
        self.frame_lst.setObjectName("frame_lst")
        self.gridLayout_6.addWidget(self.frame_lst, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.remove_frame_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_frame_btn.setObjectName("remove_frame_btn")
        self.horizontalLayout_3.addWidget(self.remove_frame_btn)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setContentsMargins(-1, -1, -1, 2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.add_frame_label_txt = QtWidgets.QLineEdit(self.groupBox)
        self.add_frame_label_txt.setObjectName("add_frame_label_txt")
        self.gridLayout_8.addWidget(self.add_frame_label_txt, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.add_frame_btn = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_frame_btn.setFont(font)
        self.add_frame_btn.setObjectName("add_frame_btn")
        self.horizontalLayout_4.addWidget(self.add_frame_btn)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 1)
        self.split_image_in_spb = QtWidgets.QSpinBox(self.groupBox)
        self.split_image_in_spb.setMinimum(1)
        self.split_image_in_spb.setMaximum(32)
        self.split_image_in_spb.setObjectName("split_image_in_spb")
        self.gridLayout_8.addWidget(self.split_image_in_spb, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frames_grb)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.frame_number_cmb = QtWidgets.QComboBox(self.groupBox_5)
        self.frame_number_cmb.setObjectName("frame_number_cmb")
        self.gridLayout_7.addWidget(self.frame_number_cmb, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 3, 0, 1, 1)
        self.preview_wide_spb = QtWidgets.QSpinBox(self.groupBox_5)
        self.preview_wide_spb.setMinimum(1)
        self.preview_wide_spb.setMaximum(16)
        self.preview_wide_spb.setObjectName("preview_wide_spb")
        self.gridLayout_7.addWidget(self.preview_wide_spb, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 3, 2, 1, 1)
        self.frame_preview = QtWidgets.QGraphicsView(self.groupBox_5)
        self.frame_preview.setObjectName("frame_preview")
        self.gridLayout_7.addWidget(self.frame_preview, 2, 0, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.frame_warnings_lbl = QtWidgets.QLabel(self.frames_grb)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.frame_warnings_lbl.setFont(font)
        self.frame_warnings_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_warnings_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.frame_warnings_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_warnings_lbl.setObjectName("frame_warnings_lbl")
        self.gridLayout_4.addWidget(self.frame_warnings_lbl, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frames_grb, 1, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.animations_grb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setContentsMargins(-1, 3, -1, 2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.start_tile_txt = QtWidgets.QLineEdit(self.groupBox_3)
        self.start_tile_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.start_tile_txt.setObjectName("start_tile_txt")
        self.gridLayout_5.addWidget(self.start_tile_txt, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.end_tile_txt = QtWidgets.QLineEdit(self.groupBox_3)
        self.end_tile_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.end_tile_txt.setObjectName("end_tile_txt")
        self.gridLayout_5.addWidget(self.end_tile_txt, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 2, 1, 1)
        self.frame_speed_cmb = QtWidgets.QComboBox(self.groupBox_3)
        self.frame_speed_cmb.setObjectName("frame_speed_cmb")
        self.frame_speed_cmb.addItem("")
        self.frame_speed_cmb.addItem("")
        self.frame_speed_cmb.addItem("")
        self.frame_speed_cmb.addItem("")
        self.frame_speed_cmb.addItem("")
        self.frame_speed_cmb.addItem("")
        self.frame_speed_cmb.addItem("")
        self.frame_speed_cmb.addItem("")
        self.gridLayout_5.addWidget(self.frame_speed_cmb, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.remove_animation_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.remove_animation_btn.setMaximumSize(QtCore.QSize(220, 16777215))
        self.remove_animation_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.remove_animation_btn.setObjectName("remove_animation_btn")
        self.horizontalLayout.addWidget(self.remove_animation_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout_5.addLayout(self.horizontalLayout, 2, 2, 1, 2)
        self.animation_number_cmb = QtWidgets.QComboBox(self.groupBox_3)
        self.animation_number_cmb.setMaximumSize(QtCore.QSize(80, 16777215))
        self.animation_number_cmb.setObjectName("animation_number_cmb")
        self.gridLayout_5.addWidget(self.animation_number_cmb, 0, 1, 1, 1)
        self.frame_quantity_cmb = QtWidgets.QComboBox(self.groupBox_3)
        self.frame_quantity_cmb.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_quantity_cmb.setObjectName("frame_quantity_cmb")
        self.frame_quantity_cmb.addItem("")
        self.frame_quantity_cmb.addItem("")
        self.frame_quantity_cmb.addItem("")
        self.frame_quantity_cmb.addItem("")
        self.frame_quantity_cmb.addItem("")
        self.gridLayout_5.addWidget(self.frame_quantity_cmb, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 4, 3, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.gridLayout_2.addWidget(self.animations_grb, 0, 2, 5, 1)
        self.gridLayout.addWidget(self.tileset_grb, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLoad_ROM = QtWidgets.QAction(mainWindow)
        self.actionLoad_ROM.setObjectName("actionLoad_ROM")
        self.actionLoad_Animation = QtWidgets.QAction(mainWindow)
        self.actionLoad_Animation.setObjectName("actionLoad_Animation")
        self.actionInsert_to_ROM = QtWidgets.QAction(mainWindow)
        self.actionInsert_to_ROM.setObjectName("actionInsert_to_ROM")
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExport_Animation = QtWidgets.QAction(mainWindow)
        self.actionExport_Animation.setObjectName("actionExport_Animation")
        self.actionImport_Animations = QtWidgets.QAction(mainWindow)
        self.actionImport_Animations.setObjectName("actionImport_Animations")
        self.actionExport_Animation_2 = QtWidgets.QAction(mainWindow)
        self.actionExport_Animation_2.setObjectName("actionExport_Animation_2")
        self.actionLoad_Tileset = QtWidgets.QAction(mainWindow)
        self.actionLoad_Tileset.setObjectName("actionLoad_Tileset")
        self.actionExport_Animations = QtWidgets.QAction(mainWindow)
        self.actionExport_Animations.setObjectName("actionExport_Animations")
        self.menuFile.addAction(self.actionLoad_ROM)
        self.menuFile.addAction(self.actionInsert_to_ROM)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionLoad_Tileset)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionImport_Animations)
        self.menuEdit.addAction(self.actionExport_Animations)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Just an Animation Editor"))
        self.tileset_grb.setTitle(_translate("mainWindow", "Tileset"))
        self.label.setText(_translate("mainWindow", "Header offset:"))
        self.add_animation_btn.setText(_translate("mainWindow", "Add Animation"))
        self.label_2.setText(_translate("mainWindow", " Preview palette:"))
        self.palette_cmb.setItemText(0, _translate("mainWindow", "0"))
        self.palette_cmb.setItemText(1, _translate("mainWindow", "1"))
        self.palette_cmb.setItemText(2, _translate("mainWindow", "2"))
        self.palette_cmb.setItemText(3, _translate("mainWindow", "3"))
        self.palette_cmb.setItemText(4, _translate("mainWindow", "4"))
        self.palette_cmb.setItemText(5, _translate("mainWindow", "5"))
        self.palette_cmb.setItemText(6, _translate("mainWindow", "6"))
        self.palette_cmb.setItemText(7, _translate("mainWindow", "7"))
        self.palette_cmb.setItemText(8, _translate("mainWindow", "8"))
        self.palette_cmb.setItemText(9, _translate("mainWindow", "9"))
        self.palette_cmb.setItemText(10, _translate("mainWindow", "10"))
        self.palette_cmb.setItemText(11, _translate("mainWindow", "11"))
        self.palette_cmb.setItemText(12, _translate("mainWindow", "12"))
        self.palette_cmb.setItemText(13, _translate("mainWindow", "13"))
        self.palette_cmb.setItemText(14, _translate("mainWindow", "14"))
        self.palette_cmb.setItemText(15, _translate("mainWindow", "15"))
        self.animations_grb.setTitle(_translate("mainWindow", "Animation"))
        self.frames_grb.setTitle(_translate("mainWindow", "Frames"))
        self.groupBox_4.setTitle(_translate("mainWindow", "All"))
        self.remove_frame_btn.setText(_translate("mainWindow", "Remove frame"))
        self.groupBox.setTitle(_translate("mainWindow", "Add"))
        self.label_10.setText(_translate("mainWindow", "Label:"))
        self.add_frame_btn.setText(_translate("mainWindow", "Import image\n"
"and add frame"))
        self.label_11.setText(_translate("mainWindow", "Split in:"))
        self.groupBox_5.setTitle(_translate("mainWindow", "Current"))
        self.label_8.setText(_translate("mainWindow", "Number:"))
        self.label_9.setText(_translate("mainWindow", "Preview wide:"))
        self.frame_warnings_lbl.setText(_translate("mainWindow", "The amount of tiles in the frame doesn\'t match the amount of tiles in the animation."))
        self.groupBox_3.setTitle(_translate("mainWindow", "General"))
        self.label_5.setText(_translate("mainWindow", "End tile:"))
        self.label_4.setText(_translate("mainWindow", "Start tile:"))
        self.label_3.setText(_translate("mainWindow", "Number:"))
        self.label_6.setText(_translate("mainWindow", "Number of frames:"))
        self.label_7.setText(_translate("mainWindow", "Speed:"))
        self.frame_speed_cmb.setCurrentText(_translate("mainWindow", "Too Fast"))
        self.frame_speed_cmb.setItemText(0, _translate("mainWindow", "Too Fast"))
        self.frame_speed_cmb.setItemText(1, _translate("mainWindow", "Very Fast"))
        self.frame_speed_cmb.setItemText(2, _translate("mainWindow", "Fast"))
        self.frame_speed_cmb.setItemText(3, _translate("mainWindow", "Normal"))
        self.frame_speed_cmb.setItemText(4, _translate("mainWindow", "Slow"))
        self.frame_speed_cmb.setItemText(5, _translate("mainWindow", "Very Slow"))
        self.frame_speed_cmb.setItemText(6, _translate("mainWindow", "Too Slow"))
        self.frame_speed_cmb.setItemText(7, _translate("mainWindow", "Is it even changing?"))
        self.remove_animation_btn.setText(_translate("mainWindow", "Remove animation"))
        self.frame_quantity_cmb.setItemText(0, _translate("mainWindow", "2"))
        self.frame_quantity_cmb.setItemText(1, _translate("mainWindow", "4"))
        self.frame_quantity_cmb.setItemText(2, _translate("mainWindow", "8"))
        self.frame_quantity_cmb.setItemText(3, _translate("mainWindow", "16"))
        self.frame_quantity_cmb.setItemText(4, _translate("mainWindow", "32"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionLoad_ROM.setText(_translate("mainWindow", "Load ROM"))
        self.actionLoad_Animation.setText(_translate("mainWindow", "Import Animation"))
        self.actionInsert_to_ROM.setText(_translate("mainWindow", "Insert to ROM"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
        self.actionExport_Animation.setText(_translate("mainWindow", "Export Animation"))
        self.actionImport_Animations.setText(_translate("mainWindow", "Import Animations"))
        self.actionExport_Animation_2.setText(_translate("mainWindow", "Export Animation"))
        self.actionLoad_Tileset.setText(_translate("mainWindow", "Load Tileset"))
        self.actionExport_Animations.setText(_translate("mainWindow", "Export Animations"))

